heat_template_version: 2014-10-16  
description: Simple Ubuntu Server  
resources:  
  server:  
    type: OS::Nova::Server  
    properties:  
      image: 'ubuntu-14.04-server-amd64'  
      flavor: m1.small  
      networks:  
        - network: External  
      user_data_format: RAW  
      user_data: |  
        #/bin/sh  
        while [ 1 ]; do echo $((13**99)) 1>/dev/null 2>&1; done & 
