heat_template_version: 2014-10-16
description: autoscaling template
resources:
  group:
    type: OS::Heat::AutoscalingGroup
    properties:
      cooldown: 60
      desired_capacity: 2
      max_size: 5
      min_size: 1
      resource:
        type: OS::Nova::Server::Ubuntu

  scaleup_policy:
    type: OS::Heat::ScalingPolicy
    properties:
      adjustement_type: change_in_capacity
      autoscaling_group_id: { get_resource: group }
      cooldown: 60
      scaling_adjustment: 1

  cpu_alarm_high:
    type: OS::Ceilometer::Alarm
    properties:
      meter_name: cpu_util
      statistic: avg
      period: 60
      evaluation_periods: 1
      threshold: 20
      alarm_actions:
        - { get_attr: [scaleup_policy, alarm_url]}
      comparison_operator: gt
